### ISSUE TITLE
hcal now available as a NetBSD package

### ISSUE THREAD

**Issue by 0323pin** [0xflotus/hcal#2]
Hi,

FYI, I've packaged and merged `hcal` into the pkgsrc main branch, https://mail-index.netbsd.org/pkgsrc-changes/2022/01/19/msg247183.html
The package should become available to the users within a day or two, depending on the build infrastructure.

Could I please ask you to provide release tags here on GitHub, which are in sync with the releases on crates.io?
No need to do it for this one but, it makes it easier for me to follow the development and provide package updates.

Thanks.
Regards,
pin@NetBSD.org

**Comment by 0xflotus** [comment]
I will pay attention to this for the next releases.

Thank you!

**Comment by 0323pin** [comment]
Thanks!

**Comment by 0323pin** [comment]
Hi,

Would you mind to provide release tags here on GitHub.
Doing so, allows me to follow the project through atom feeds. Right now, without these, the only way to find out about new releases, is a random visit to crates.io

Thanks

**Comment by 0xflotus** [comment]
> Hi,
> 
> Would you mind to provide release tags here on GitHub. Doing so, allows me to follow the project through atom feeds. Right now, without these, the only way to find out about new releases, is a random visit to crates.io
> 
> Thanks

Something [like this](https://github.com/0xflotus/hcal/releases)?

**Comment by 0323pin** [comment]
Perfect, thanks!
Added to my feeds
